---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "currency-server-chart.fullname" . }} -secrets
type: Opaque
data:
  MDB_USERNAME: "{{ .Values.serverSettings.mdbUsername | default "" | b64enc}}"
  MDB_PASSWORD: "{{ .Values.serverSettings.mbdPassword | default "" | b64enc}}"
  MDB_CLUSTER: "{{ .Values.serverSettings.mdbCluster | default "" | b64enc}}"
  MDB_APPNAME: "{{ .Values.serverSettings.mdbAppName | default "" | b64enc}}"