name: Build Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: List files
        run: ls -R

      - name: Docker meta for currency
        id: meta_currency
        uses: docker/metadata-action@v5
        with:
          images: |
            amitsuresh/server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Docker meta for product-api
        id: meta_product
        uses: docker/metadata-action@v5
        with:
          images: |
            amitsuresh/product-api
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push currency server
        uses: docker/build-push-action@v2
        with:
          context: ./playservices/v14/currency/
          file: ./playservices/v14/currency/Dockerfile
          push: true
          tags: ${{ steps.meta_currency.outputs.tags }}

      - name: Build and push product-api
        uses: docker/build-push-action@v2
        with:
          context: ./playservices/v14/product-api/
          file: ./playservices/v14/product-api/Dockerfile
          push: true
          tags: ${{ steps.meta_product.outputs.tags }}
